### ISSUE TITLE
Sign text value might not be updated?

### ISSUE THREAD

**Issue by prototype464** [GregoryAM-SP/The-Minecraft-Overviewer#72]
I'd like to start off by mentioning this worked using the old Overviewer, so around ~1.17.1. I'm not a programmer nor smart enough to solve the error myself as it looks like it's just down to a misconfiguration but I believe the Text1, Text2. etc. values on signs were update at some point which is probably why this isn't working. Or this is just a bug. Eitherway, thanks for maintaining this! :>

My config:
`global escape
from html import escape
def signFilter(poi):
    if poi['id'] == 'Sign' or poi['id'] == 'minecraft:sign':
        return escape("\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']]))
def chestFilter(poi):
    if poi['id'] == "Chest" or poi['id'] == 'minecraft:chest':
        if "LootTable" in poi:
            return None
        else:
            return "Chest with %d items" % len(poi.get('Items', []))
def playerIcons(poi):
    if poi['id'] == 'Player':
        poi['icon'] = "" % poi['EntityId']
        return "Last known location for %s" % poi['EntityId']

worlds["empirepvp"] = r"C:\Users\james\AppData\Roaming\PolyMC\instances\Main (Modded) [1.20.4]\.minecraft\saves\empirepvp"

renders["normalrender"] = {
    "world": "empirepvp",
    "title": "CarekCabinSearch",
    "dimension": "overworld",
    "rendermode": "normal",
    "imgformat": "jpeg",
    "imgquality": "90",
    "texturepath": r"C:\Users\james\Documents\Data_Programs\Game\Minecraft\Overviewer\resourcepacks\java_vanilla",
    "markers": [dict(name="All Signs", filterFunction=signFilter, icon="oak_sign.png", createInfoWindow=True), dict(name="Chests", filterFunction=chestFilter, icon="chest.png", createInfoWindow=True)]
}

outputdir = r"C:\Users\james\Documents\Data_Programs\Game\Minecraft\Overviewer_Renders"`

The error:
`2024-06-04 00:21:10 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "multiprocessing\pool.py", line 125, in worker
  File "multiprocessing\pool.py", line 48, in mapstar
  File "overviewer_core\aux_files\genPOI.py", line 138, in parseBucketChunks
  File "C:\Users\james\Documents\Data_Programs\Game\Minecraft\overviewer_config.py", line 5, in signFilter
    return escape("\n".join([poi['Text1'], poi['Text2'], poi['Text3'], poi['Text4']]))
KeyError: 'Text1'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "overviewer.py", line 653, in <module>
  File "overviewer.py", line 168, in main
  File "overviewer_core\aux_files\genPOI.py", line 604, in main
  File "overviewer_core\aux_files\genPOI.py", line 233, in handleEntities
  File "multiprocessing\pool.py", line 364, in map
  File "multiprocessing\pool.py", line 768, in get
KeyError: 'Text1'`

**Comment by prototype464** [comment]
Oh wait, this can be closed. Oops.
https://github.com/GregoryAM-SP/The-Minecraft-Overviewer/issues/5
